#!/bin/bash -e

BRANCH=$(git rev-parse --abbrev-ref HEAD);
IFS='-' read -ra PARTS <<< "$BRANCH"
if [ "${PARTS[0]}" != "issue" ]; then
	echo "Current branch is not issue related" 1>&2
	exit 1;
fi
echo ${PARTS[1]};
